# .circleci/config.yml
version: 2
jobs:
  train_and_test:
    # ... same as previous code snippet
  deploy_staging:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy app to staging
          command: bin/deploy_to_heroku.sh ci-workshop-app-lly-staging

workflows:
  version: 2
  my_ci_pipeline:
    jobs:
      - train_and_test
      - deploy_staging:
          requires:
            - train_and_test

